- name: Ensure python docker SDK is available
  hosts: all
  become: true
  tasks:
    - name: Ensure python3-docker is present
      apt:
        name: python3-docker
        state: present
        update_cache: true
