- name: Ensure Docker and Python Docker SDK are installed and running
  hosts: all
  become: true
  tasks:
    - name: Install Docker
      apt:
        name:
          - docker.io
          - python3-docker
        state: present
        update_cache: true

    - name: Enable and start Docker
      systemd:
        name: docker
        enabled: true
        state: started
