- name: Ensure docker SDK for Python is installed
  hosts: all
  become: true
  tasks:
    - name: Ensure pip3 is present
      apt:
        name: python3-pip
        state: present
        update_cache: true

    - name: Ensure docker module is installed for Python
      pip:
        name: docker
        executable: pip3
