name: Terraform plan/apply CI/CD

on:
  workflow_call:
    inputs:
      matrix:
        required: true
        type: string

jobs:
  plan:
    name: Terraform Plan (on PR)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: ${{ fromJson(inputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/tf-common
        with:
          env: ${{ matrix.env }}
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Download tfvars
        uses: actions/download-artifact@v3
        with:
          name: tfvars
          path: envs

      - name: Terraform Plan
        working-directory: "tf"
        run: |
          terraform workspace select -or-create ${{ matrix.env }}
          terraform plan -var-file="envs/${{ matrix.env }}.tfvars.json"
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/account.json

    concurrency:
      group: ${{ github.workflow }}-${{ matrix.env }}
      cancel-in-progress: true
