name: Terraform plan CI/CD

on:
  workflow_call:
    inputs:
      matrix:
        required: true
        type: string

jobs:
  plan:
    name: Terraform Plan (on PR)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{ fromJson(inputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/tf-common
        with:
          env: ${{ matrix.name }}
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Download tfvars
        uses: actions/download-artifact@v4
        with:
          name: tfvars
          path: tf/envs

      - run: |
          echo "Deploying for env: ${{ matrix.name }}"

      - name: Terraform Plan
        working-directory: "tf"
        run: |
          terraform workspace select -or-create "${{ matrix.name }}"
          terraform plan -var-file="envs/${{ matrix.name }}.tfvars.json"
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/account.json

      - name: Cleanup Terraform lock for ${{ matrix.name }}
        if: always()
        run: |
          echo "Removing lock for env: ${{ matrix.name }}"
          gsutil rm -f gs://modelyo-tf-states-bucket/terraform/state/${{ matrix.name }}.tflock || true

    concurrency:
      group: ${{ github.workflow }}-${{ matrix.name }}
      cancel-in-progress: true
